const site_name = 'fandao',
  path_http = 'include/http/',
  path_view = 'view/',
  path_css = 'view/css/',
  path_html = 'https://fandao.fun/',
  path_aifadian_oauth = `https://afdian.com/oauth2/authorize?response_type=code&scope=basic&client_id=${site_name}&redirect_uri=${path_html}oauth.php&state=111`,
  path_explorer = 'https://whiteverse.com/explorer.html?planet=',
  text_login_please = "<i class='fa-solid fa-circle-exclamation'></i>&nbsp;没有登录，怎么会这样？",
  text_no_enough_balance = `<i class="fa-solid fa-battery-empty"></i>&nbsp;余额不足。`,
  text_doodle_solitaire = '<a class="fandaoDoodleSolitaire"><i class="fa-solid fa-images"></i>&nbsp;接龙</a>',
  text_upload_success = '<i class="fa-solid fa-circle-check"></i>&nbsp;上传成功，请随意调整位置。',
  text_upload_fail = '<i class="fa-solid fa-face-sad-tear"></i>&nbsp;文件类型不符或尺寸过大',
  text_dice = '[[d6]]',
  text_theme_darkmode = '&nbsp;黑暗模式',
  text_theme_lightmode = '&nbsp;明亮模式',
  text_unsubscribe = '<i class="fa-solid fa-xmark"></i>&nbsp;取消订阅',
  text_subscribe = '<i class="fa-solid fa-bookmark"></i>&nbsp;订阅',
  text_thumbsUpIcon = '<i class="fa-solid fa-thumbs-up"></i>',
  text_post = 'PO',
  text_reply = '回复',
  text_post_too_fast = '请求过于频繁，请歇会儿。',
  text_empty_title = '请输入提议标题',
  text_empty_content = '请输入内容',
  text_wrong_category = '来到了不存在的分区？<br><small>马上送你回去。</small>',
  text_error_fatal = 'E2:未知错误。',
  text_transfer_success = '转账成功',
  text_operation_failed = '操作失败。',
  text_switch_avatar_success = '切换成功，转到首页生效。',
  text_sent_verify_mail = '<i class="fa-solid fa-circle-info"></i>&nbsp;已发送，请前往邮箱查收！',
  text_error_transfer_amount = '数额错误',
  text_error_transfer_address = '目标地址错误',
  text_error_password_length = '请输入6-16位密码',
  text_error_wrong_username = '用户名格式有误，仅"-","_",数字,字母(区分大小写)',
  text_error_taken_email = '这个名字或邮箱已经被取了',
  text_error_different_password = '两次密码不一致',
  text_error_same_password = '新旧密码没有区别。',
  text_change_done = '修改成功！',
  text_chage_failed = '修改失败！',
  text_error_wrong_name_or_password = "<i class='fa-solid fa-circle-exclamation'></i>&nbsp;用户名或密码错误",
  text_registering_air = '在注册空气吗？',
  text_error_wrong_mail = '邮箱格式有误',
  text_banned_for_days = '已封禁7天。',
  text_confirm = '确定',
  text_unbanned = '已解封。',
  text_changed_user_level = '已改变该用户的用户组。',
  text_password_please = "<i class='fa-solid fa-circle-exclamation'></i>&nbsp;请输入密码",
  text_has_been_bound = "<i class='fa-solid fa-circle-exclamation'></i>&nbsp;该账户已绑定至其他饭岛用户",
  text_negative_amount = '<i class="fa-regular fa-face-grin-squint"></i>&nbsp;竟有这种好事？',
  text_chart_historical_price = '历史价格',
  text_property_zero_price = '<i class="fa-solid fa-hand"></i>&nbsp;请通过其他方式白送~',
  text_questionmark_pointdown = '<i class="fa-solid fa-hand-point-down"></i>&nbsp;？',
  text_wikiscore_add = '<i class="fa-regular fa-face-grin-wink"></i>&nbsp;比上次增加了',
  text_wikiscore_score2uct = '<i class="fa-regular fa-circle-check"></i>&nbsp;积分<i class="fa-solid fa-right-long"></i>UCT：',
  text_wikiscore_minus = '<i class="fa-solid fa-skull"></i>&nbsp;比上次减少了',
  text_pension_charging = '<i class="fa-solid fa-handcuffs"></i>&nbsp;收取UCT服务费',
  text_wikiscore_nochange = '<i class="fa-solid fa-user-clock"></i>&nbsp;基本没有变化。',
  text_wikiscore_come_next_day = '<i class="fa-regular fa-hand fa-shake"></i>&nbsp;下次再来!',
  text_property_inspect = '查看',
  text_property_sell = '出售',
  text_property_buy = '购买',
  avatar_fandao_cn = '饭岛基金会',
  avatar_fandao = 'fandao',
  avatar_avatar = 'avatar',
  avatar_avatar_cn = '饭岛化身管理局',
  avatar_ip = 'ip',
  avatar_ip_cn = '饭岛知识产权管理局',
  avatar_lottery = 'lottery',
  avatar_lotterry_cn = '饭岛海鸥彩票基金会',
  avatar_blackhole = 'blackhole',
  avatar_blackhole_cn = '黑洞';
